server:
  port: ${SERVER_PORT:8088}
spring:
  config:
    name: movie-manager
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: false
    hibernate:
      ddl-auto: none
    show-sql: false
    database: postgresql
    properties:
      hibernate:
        generate_statistics: false
        jdbc:
          time_zone: UTC
      jdbc:
        batch_size: 100
      order_inserts: true
      order_updates: true
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:postgres}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:password}
    driver-class-name: org.postgresql.Driver
  flyway:
    baseline-on-migrate: true
    baseline-version: 0.0
admin:
  name: ${ADMIN_NAME:Artemii}
  username: ${ADMIN_USERNAME:artemii.aleksenko}
  password: ${ADMIN_PASSWORD:password}