-- TABLES
CREATE TABLE FILM_MEMBERS
(
    ID          BIGSERIAL PRIMARY KEY,
    FIRST_NAME  VARCHAR(255) NOT NULL,
    LAST_NAME   VARCHAR(255) NOT NULL,
    BIRTHDAY    DATE         NOT NULL,
    NATIONALITY VARCHAR(255) NOT NULL
);

CREATE TABLE FILMS
(
    ID           BIGSERIAL PRIMARY KEY,
    TITLE        VARCHAR(1000) NOT NULL,
    POSTER_URl   VARCHAR(2500) NOT NULL,
    RELEASE_DATE DATE          NOT NULL,
    PLOT         TEXT          NOT NULL
);

CREATE TABLE ROLES
(
    ID        BIGSERIAL PRIMARY KEY,
    CHARACTER VARCHAR(255) NOT NULL,
    ACTOR_ID  BIGINT       NOT NULL CONSTRAINT FK_ACTOR_ROLES_ID REFERENCES FILM_MEMBERS (ID) ON DELETE CASCADE ON UPDATE CASCADE,
    FILM_ID   BIGINT       NOT NULL CONSTRAINT FK_FILM_ROLES_ID REFERENCES FILMS (ID) ON DELETE CASCADE ON UPDATE CASCADE,
    FEE       NUMERIC(14, 2)
);


CREATE TABLE FILM_CREATORS
(
    ID           BIGSERIAL PRIMARY KEY,
    CREATOR_ID   BIGINT NOT NULL CONSTRAINT FK_CREATOR_ID REFERENCES FILM_MEMBERS (ID) ON DELETE CASCADE ON UPDATE CASCADE,
    FILM_ID      BIGINT NOT NULL CONSTRAINT FK_FILM_CREATOR_ID REFERENCES FILMS (ID) ON DELETE CASCADE ON UPDATE CASCADE,
    CREATOR_ROLE VARCHAR(50) NOT NULL
);

CREATE TABLE COUNTRIES
(
    ID      BIGSERIAL PRIMARY KEY,
    COUNTRY VARCHAR(255) NOT NULL
);

CREATE TABLE FILM_COUNTRY
(
    COUNTRY_ID BIGINT NOT NULL CONSTRAINT FK_COUNTRY_COUNTRY_FILM_ID REFERENCES COUNTRIES (ID) ON DELETE CASCADE ON UPDATE CASCADE,
    FILM_ID    BIGINT NOT NULL CONSTRAINT FK_FILM_COUNTRY_FILM_ID REFERENCES FILMS (ID) ON DELETE CASCADE ON UPDATE CASCADE
);

-- CONSTRAINTS
ALTER TABLE COUNTRIES ADD CONSTRAINT uq_country UNIQUE (COUNTRY);

-- INDEXES
CREATE INDEX FILM_MEMBERS_first_last_name_id ON FILM_MEMBERS(first_name, last_name);


-- SECURITY
CREATE TABLE APP_ROLES
(
    ID   BIGSERIAL PRIMARY KEY,
    NAME VARCHAR(20)
);

CREATE TABLE APP_USERS
(
    ID   BIGSERIAL PRIMARY KEY,
    NAME VARCHAR(50),
    USERNAME VARCHAR(255),
    PASSWORD VARCHAR(255)
);

CREATE TABLE USER_ROLE
(
    USER_ID BIGINT NOT NULL CONSTRAINT FK_APP_USER_ID REFERENCES APP_USERS (ID) ON DELETE CASCADE,
    ROLE_ID BIGINT NOT NULL CONSTRAINT FK_APP_ROLE_ID REFERENCES APP_ROLES (ID) ON DELETE CASCADE
);